# Generated by Django 4.2.15 on 2025-03-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discrepancies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discrepancyannotation",
            name="annotation",
        ),
        migrations.RemoveField(
            model_name="discrepancyannotation",
            name="discrepancy",
        ),
        migrations.RemoveField(
            model_name="discrepancyannotation",
            name="user",
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
        migrations.DeleteModel(
            name="DiscrepancyAnnotation",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
