# Generated by Django 4.2.15 on 2025-03-31 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0008_assignment"),
        ("discrepancies", "0002_remove_discrepancyannotation_annotation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discrepancy",
            name="example",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discrepancies",
                to="examples.example",
            ),
        ),
        migrations.AddField(
            model_name="discrepancy",
            name="labels",
            field=models.JSONField(default=list),
        ),
    ]
