# Generated by Django 4.2.15 on 2025-03-31 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0008_assignment"),
        ("discrepancies", "0003_discrepancy_example_discrepancy_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discrepancy",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="discrepancies", to="examples.example"
            ),
        ),
    ]
